# Generated by Django 3.1.4 on 2020-12-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201002_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=10, null=True)),
                ('make', models.CharField(blank=True, max_length=12, null=True)),
                ('color', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=400)),
                ('seat_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.CharField(blank=True, max_length=10, null=True)),
                ('rate', models.CharField(blank=True, max_length=10, null=True)),
                ('current_mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
